# Generated by Django 2.2.3 on 2019-07-13 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttype',
            name='account_type',
            field=models.CharField(max_length=20),
        ),
    ]
