# Generated by Django 2.2.3 on 2019-07-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='month_intervals',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
