# Generated by Django 2.2.3 on 2019-07-13 07:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paychecks', '0001_initial'),
        ('accounts', '0004_auto_20190713_0255'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('contribution_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('month_intervals', models.IntegerField()),
                ('account_type_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.AccountType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MoneyAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contribution_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('month_intervals', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('date_opened', models.DateField(default=datetime.datetime.now)),
                ('date_closed', models.DateField(blank=True, null=True)),
                ('account_type_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.AccountType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True, null=True)),
                ('transaction_date', models.DateField()),
                ('amount_spent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('budget_account_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.BudgetAccount')),
                ('money_account_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.MoneyAccount')),
                ('paystub_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paychecks.Paystub')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
