# Generated by Django 2.2.3 on 2019-07-16 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190713_0318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budgetaccount',
            old_name='account_type_id',
            new_name='account_type',
        ),
        migrations.RenameField(
            model_name='moneyaccount',
            old_name='account_type_id',
            new_name='account_type',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='budget_account_id',
            new_name='budget_account',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='money_account_id',
            new_name='money_account',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='paystub_id',
            new_name='paystub',
        ),
    ]
