# Generated by Django 2.2.3 on 2020-02-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paychecks', '0005_assigned_budget_paycheck'),
        ('accounts', '0009_assigned_budget_paycheck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetaccount',
            name='assigned_paycheck',
        ),
        migrations.AddField(
            model_name='budgetaccount',
            name='assigned_paycheck',
            field=models.ManyToManyField(blank=True, null=True, to='paychecks.Paycheck'),
        ),
    ]
