# Generated by Django 2.2.3 on 2020-02-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_assigned_budget_paycheck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetaccount',
            name='assigned_paycheck',
            field=models.ManyToManyField(blank=True, to='paychecks.Paycheck'),
        ),
    ]
