# Generated by Django 2.2.3 on 2020-08-10 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_assigned_budget_paycheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneyaccount',
            name='is_brokerage',
            field=models.BooleanField(default=False),
        ),
    ]
