# Generated by Django 2.2.3 on 2020-08-17 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0012_moneyaccount_is_brokerage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('ticker', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('asset_class', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockShares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brokerage_account', models.ForeignKey(blank=True, limit_choices_to={'is_brokerage': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.MoneyAccount')),
                ('budget_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.BudgetAccount')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='shares', to='stocks.Stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('transaction_type', models.CharField(choices=[('B', 'Buy'), ('S', 'Sell')], max_length=2)),
                ('num_shares', models.DecimalField(decimal_places=4, max_digits=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shares', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='stocks.StockShares')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
