# Generated by Django 2.2.3 on 2021-02-24 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_auto_20210104_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockshares',
            name='brokerage_account',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_brokerage': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='shares', to='accounts.MoneyAccount'),
        ),
        migrations.AlterField(
            model_name='stockshares',
            name='budget_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='shares', to='accounts.BudgetAccount'),
        ),
        migrations.AlterField(
            model_name='stockshares',
            name='num_shares',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='num_shares',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
    ]
