# Generated by Django 5.2.1 on 2026-04-10 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0005_auto_20230310_0051"),
    ]

    operations = [
        migrations.AddField(
            model_name="stocktransaction",
            name="to_shares",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="transfers_in",
                to="stocks.stockshares",
            ),
        ),
        migrations.AlterField(
            model_name="stockshares",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="stocktransaction",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="stocktransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[("B", "Buy"), ("S", "Sell"), ("T", "Transfer")], max_length=2
            ),
        ),
    ]
