# Generated by Django 2.2.3 on 2019-07-10 22:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paycheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('annual_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paychecks_per_year', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PayType',
            fields=[
                ('paychecks_per_year', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Paystub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('creation_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('paycheck', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='paychecks.Paycheck')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('deduction_type', models.CharField(choices=[('Pre-Tax', 'Pre-Tax'), ('Post-Tax', 'Post-Tax')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('active', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('paycheck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paychecks.Paycheck')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
