# Generated by Django 2.2.3 on 2019-07-21 19:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paychecks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paycheck',
            name='creation_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
