# Generated by Django 2.2.3 on 2019-07-26 21:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('paychecks', '0002_auto_20190721_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deduction',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 26, 21, 48, 34, 987960, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='paycheck',
            name='creation_date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 7, 26, 21, 48, 34, 986974, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='paystub',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 26, 21, 48, 34, 988648, tzinfo=utc)),
        ),
    ]
