# Generated by Django 2.2.3 on 2020-02-18 18:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('paychecks', '0003_auto_20190726_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deduction',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 18, 18, 59, 18, 879772, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='paycheck',
            name='creation_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 2, 18, 18, 59, 18, 878616, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='paystub',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 18, 18, 59, 18, 880541, tzinfo=utc)),
        ),
    ]
